[package]
name = "the-matrix"
version = "0.1.0"
authors = ["Abhimanyu Mongandh Ambalath <abhi@manyu.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"